[workspace]
channels = ["conda-forge", "bioconda", "bioconda", "conda-forge"]
name = "GWAS-Biobank"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
openjdk = "11.0.29.*"

[pypi-dependencies]
hail = ">=0.2.137, <0.3"
pixi-kernel = ">=0.7.1, <0.8"
