[workspace]
channels = ["conda-forge", "bioconda", "bioconda", "conda-forge"]
name = "gwas-biobank"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
bcftools = ">=1.22,<2"
r-base = ">=4.5.2,<4.6"
python = "3.12.*"
r-tidyverse = ">=2.0.0,<3"
r-ggpubr = ">=0.6.2,<0.7"
r-ggprism = ">=1.0.7,<2"
r-rcolorbrewer = ">=1.1_3,<2"
r-glue = ">=1.8.0,<2"
r-patchwork = ">=1.3.2,<2"
openjdk = "11.0.29.*"
awscli = ">=2.31.37,<3"
tabix = ">=1.11,<2"
r-gt = ">=1.2.0,<2"
r-gtsummary = { version = ">=2.5.0,<3", channel = "conda-forge" }

[pypi-dependencies]
pixi-kernel = ">=0.7.0, <0.8"
pandas = ">=2.3.3, <3"
hail = "==0.2.136"
certifi = ">=2025.11.12, <2026"
liftover = ">=1.3.3, <2"
aouprs = ">=0.2.6, <0.3"